apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
spec:
  destination:
    namespace: sync-waves
    name: in-cluster
  project: default
  source:
    path: sync-waves/
    repoURL: https://github.com/morey-tech/argocd-v2.11-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true